title: 'CoderDojo Deutschland'
default_lang: de
author:
  name: 'CoderDojo Deutschland Team'
  email: mail@coderdojo-deutschland.de
taxonomies:
  - category
  - tag
metadata:
  description: 'Programmierklubs für Kinder und Jugendliche'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
